[package]
name = "cp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
eval = "0.4.3"
itertools = "0.10.5"
radix_fmt = "1.0.0"
rand = "0.8.5"
regex = "1.8.1"
