[project]
name = "cp"
version = "0.1.0"
description = "Solutions to Leet Code, UVa, Advent of Code, etc. problems"
authors = [{ name = "giprayogo" }]

readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.12.2",
]
